### ISSUE TITLE
Too easy to crack

### ISSUE THREAD

**Issue by Ian321** [SNBSLibs/Licensing.ActivationKeys#16]
Hi! I just saw this on HN and have a question: Why?

- Shipping this library to a customer would require embedding the SQL credentials, which would expose at least read access to each license, and at worst full access to the database.
- Using this on the back-end would require implementing another license checker in the client.

Finally: You do not want a single class or function to check the validity of a license, as this provides a single point in the program that can easily be patched to bypass the check.

**Comment by SNBSLibs** [comment]
Oh, I've missed that fact — SQL credentials have to be embedded. My bad. But what would you *suggest* to fix it? (Sorry but I can't work on my library right now.)

**Comment by Ian321** [comment]
You could make the client query an HTTP endpoint instead of accessing the database directly.
And to prevent easy cracking, you could inject the license check into multiple parts of the program using roslyn.

**Comment by SNBSLibs** [comment]
What about HTTP API — I've already received the same feedback on HN. I now understand that using direct database connection was a bad idea. The next major version (2.0.0) is going to implement HTTP API.

What about injecting license check into multiple parts of the program — it's a new idea, taken into account. Thanks!

**Comment by SNBSLibs** [comment]
The project of library v2 (using HTTP to serve clients) is ready. I'm starting to  implement it on 22 April.

Splitting the license check is planned for next versions (lots of work, one person).

**Comment by SNBSLibs** [comment]
Issue closed due to the repository being archived (development was stopped for internal reasons).
