### ISSUE TITLE
How to create the table Licenses

### ISSUE THREAD

**Issue by chenscottus** [SNBSLibs/Licensing.ActivationKeys#17]
Hello,

     I created a new account in www.freesqldatabase.com.  I wonder, How to create the table Licenses? Do you have the sql query for that?

     Whenever I run admin.cs or client.cs, here is the error message:
       - This message;
- The exception message: "An error occurred (see the inner exception) when querying the licenses database. This can be caused by invalid connection string, modifications to the database structure (they're a bad idea!) etc.";
- The inner exception message: "Table 'sqlxxxxxx.Licenses' doesn't exist".
Thank you!

**Comment by SNBSLibs** [comment]
Hello!

I'm sorry I couldn't answer sooner.

You can query the created database using [phpMyAdmin](https://phpmyadmin.co). The server, username and password are in your FreeSqlDatabase account.

In fact, the library creates the table itself, as the unit tests show. Although, if it doesn't, you can use this query:

```
CREATE TABLE [dbo].[Licenses] (
  [Key]  char(29) NOT NULL,
  [Expiration] datetime2 NOT NULL,
  [Type] varchar(12) NOT NULL,
  [MaxDevices] smallint NOT NULL,
  [UsingDevices] smallint NOT NULL
);
```

**Comment by SNBSLibs** [comment]
Issue closed due to the repository being archived (development was stopped for internal reasons).
