### ISSUE TITLE
No support for renewal keys (VOTING)

### ISSUE THREAD

**Issue by SNBSLibs** [SNBSLibs/Licensing.ActivationKeys#9]
This library doesn't offer an easy-to-use mechanism to create and use renewal keys — to use an expired license for longer time.

**Anybody using my library is kindly asked to comment on this issue and tell me if such mechanism is worth adding.**

**Comment by hmirheydari** [comment]
@SNBSLibs This mechanism is useful and addition is recommended.

**Comment by SNBSLibs** [comment]
@hmirheydari Thank you! The development is now paused, but your request is taken into account.
